apiVersion: argoproj.io/v1alpha1
kind: Application 
metadata:
  name: pg-shop
  namespace: argocd 
spec:
  project: default 
  source:
    repoURL: "https://github.com/rajesh20032003/revision"
    targetRevision: HEAD 
    path: apps 
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: shop
  ignoreDifferences:
    - group: apps
      kind: Deployment 
      jsonPointers:
        - /spec/replicas 
    - group: ""
      kind: Secret
      jsonPointers:
        - /metadata/annotations/control-plane.alpha.kubernetes.io~1leader 
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 