apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata: 
  name: shop-env 
  namespace: argocd 
spec:
  generators:
    - list:
       elements: 
         - env: stage
         - env: prod 
         - env: dev 
  template:
    metadata:
      name: 'shop-env-{{env}}'
    spec:
      project: shop-project 
      source:
        repoURL: "https://github.com/rajesh20032003/revision"
        targetRevision: HEAD 
        path: k8s
      destination: 
        server: "https://kubernetes.default.svc"
        namespace: "shop-{{env}}"
      syncPolicy:
        automated:
          prune: true 
          selfHeal: true 
        syncOptions:
          - createNamespace=true 