apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  name: allow-client-a 
  namespace: shop-dev
spec:
  selector:
    matchLabels:
      app: my-app
  action: ALLOW 
  rules:
    - from:
        - source:
            principals:
               - "cluster.local/ns/shop-dev/client-a"