apiVersion: security.istio.io/v1
kind: RequestAuthentication
metadata:
  name: deploy-app-jwt
  namespace: shop-dev
spec:
  selector:
    matchLabels:
      app: my-app
  jwtRules:
    - issuer: "testing@secure.istio.io"
      jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.30/security/tools/jwt/samples/jwks.json"