{{- range .Values.services }}
apiVersion: v1
kind: Service 
metadata:
  name: {{ .name }} 
  namespace: {{ $.Release.Namespace }}
spec:
  selector: 
    app: {{ .name }}
  type: {{ .type }}
  ports: 
    - protocol: TCP 
      port: {{ .port }}
      targetPort: {{ .targetPort }}
---
{{- end }}