FROM node:22-alpine as builder 
WORKDIR /app 
COPY package*.json .
RUN npm ci #installs dep for both prod and dev
COPY . . 
RUN npm run build 

FROM node:22-alpine 
WORKDIR /app 
COPY package*.json .
RUN addgroup -S raj && adduser -S raj -G raj
RUN npm ci --omit=dev #installs only prod dep
COPY --from=builder --chown=raj:raj /app/dist ./dist
USER raj  
ENV PORT=8080
EXPOSE 8080
CMD ["node", "dist/index.js"]