apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: loki
    targetRevision: "*"
    helm:
      values: |
        deploymentMode: SimpleScalable
        loki:
          auth_enabled: false
          commonConfig:
            replication_factor: 1
          storage:
            type: s3
            bucketNames:
              chunks: s3-loki-bucket-rajesh
              ruler: s3-loki-bucket-rajesh
              admin: s3-loki-bucket-rajesh
            s3:
              region: us-east-1
              s3ForcePathStyle: false
        read:
          replicas: 2
          extraEnvFrom:
            - secretRef:
                name: loki-s3-secret
        write:
          replicas: 2
          extraEnvFrom:
            - secretRef:
                name: loki-s3-secret
        backend:
          replicas: 2
          extraEnvFrom:
            - secretRef:
                name: loki-s3-secret
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true